grid_params:
  network:
    1: 
      l1: [64, 'relu', 0.1, 0, 0]
      l2: [1,'sigmoid',0, 0, 0]
    2: 
      l1: [16, 'relu', 0.1, 0.05, 0]
      l2: [1,'sigmoid',0, 0, 0]
    3:
      l1: [32, 'relu', 0.1, 0, 0.05]
      l2: [1,'sigmoid',0, 0, 0]
    4:
      l1: [64, 'relu', 0.10, 0, 0]
      l2: [16, 'relu', 0.10, 0, 0]
      l3: [1,'sigmoid',0, 0, 0]
    5:
      l1: [32, 'relu', 0.10, 0.05, 0.00]
      l2: [16, 'relu', 0.10, 0.05, 0.00]
      l3: [1,'sigmoid',0, 0, 0]
    6:
      l1: [32, 'relu', 0.10, 0, 0.05]
      l2: [16, 'relu', 0.10, 0, 0.05]
      l3: [1,'sigmoid',0, 0, 0]
  epochs: 
    - 500
    - 100
  batch_size: 
    - 256
    - 512
  optimizer: 
    - 'adam'
    - 'sgd'
keras_callbacks: []
mode: 'randomized_search' # grid_search | randomized_search
cv_params:
  n_jobs: -1
  cv: 6
  verb: 1
  scoring: 'accuracy'
  n_iter: 10